### ISSUE TITLE
issue-1-user-can-see-their-car

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/driving-game#1]
![image](https://user-images.githubusercontent.com/99565410/163608560-7b3ceed1-ae3c-4bee-bb92-70b13d4b4552.png)
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML, CSS & JS files and link to HTML
- [x] Color the floor (background color) 
- [x] Add div[class="image-container] holding the car
- [x] Add image of car to the image-container
- [x] Set the position of the image-container to absolute
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
