### ISSUE TITLE
issue-2-turn-car

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/driving-game#3]
![68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d7475726e2d74686569722d6361722e676966](https://user-images.githubusercontent.com/99565410/163620823-2afa54c0-7f3a-4853-8417-62852e263172.gif)

## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a CSS ruleset named rotate-right - transform: rotate(90deg). 
- [x] Create a CSS ruleset rotate-left-  transform: rotate(-90deg). 
- [x] Create a CSS ruleset rotate-opposite- transform: rotate(180deg). (Face opposite way)
- [x] Create a DOM element $car for the image-container.
- [x] Add an .addEventListener to the window for 'keydown' events with the function handleDirection
- [x] Create a function handleDirection
  - [x] if event key is ArrowRight, change class name to 'image-container'
  - [x]  if event key is ArrowDown, change class name to 'image-container rotate-right'
  - [x]  if event key is ArrowLeft, change class name to 'image-container rotate-opposite'
  - [x]  if event key is ArrowUp, change class name to 'image-container rotate-left'
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
