### ISSUE TITLE
issue-3-start-car

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/driving-game#5]
![68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d73746172742d74686569722d6361722e676966](https://user-images.githubusercontent.com/99565410/163628378-514eb795-17ff-45df-ac2c-7bc81137ffa9.gif)

## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List
- [x] Create a data model for your car and give it X and Y properties
- [x] Ensure that your image has a position property of absolute value
- [x] Add a top and left property to the image-container
- [x] Add an if statement to the handleDirection function, listening for the Spacebar event key
  - [x] If spacebar is clicked, setInterval to start the car and increment the left property by 10, every 16 ms
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
