### ISSUE TITLE
issue-4-stop-car

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/driving-game#7]
![68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d73746f702d74686569722d6361722e676966](https://user-images.githubusercontent.com/99565410/163649408-15370e9d-c378-4d18-8b09-77ac2e3ee164.gif)

## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add carMoving property to carModel data model and assign it to false
- [x] In your current if statement conditional, add '&& carMoving === false'
- [x] When spacebar event listener is triggered, assign carMoving property to true
- [x] Add another if statement when your spacebar event listener is triggered 
- [x] Add condition to new if statement, '&& carMoving === true'
- [x]  If carMoving === true, clearInterval on intervalID
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
