### ISSUE TITLE
issue-5-steer-car

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/driving-game#9]
![68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d73746565722d74686569722d6361722e676966](https://user-images.githubusercontent.com/99565410/163650145-9e0ea98b-f4c4-4bbf-86f5-9ea2f99e5c00.gif)

## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] If an event.key is triggered while carMoving is true
  - [x] If arrowDown is triggered, stop X, increment Y by 10
  - [x] If arrowLeft is triggered, stop Y, decrement X by 10
  - [x] If arrowUp is triggered, stop X, decrement Y by 10
  - [x] If arrowRight is triggered, stop Y, increment X by 10
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ]Test all functionality again in a private browsing session.
- [ ]Fix all errors.
